### ISSUE TITLE
needs short lab

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/reading-ios-using-tests#6]
would be helpful to provide short lab with test suite. Otherwise I am left to imagine what test suite file structure looks like, where things are located, etc. 

@markedwardmurray

**Comment by AnnJohn** [comment]
Iceboxing for now. @markedwardmurray close when you're done with the issue.

**Comment by markedwardmurray** [comment]
addressed by https://github.com/learn-co-curriculum/objc-palindrome-inspector
